/**
 * Story 4.1 — user-message payload for the `letter.generate` job.
 *
 * Strict: never include LOINC codes or extraction-confidence scores
 * in the patient-facing prompt (architecture enforcement rule 6,
 * line 900). The patient prompt is summary-shaped — one line per
 * biomarker, with the lab name + collection date + value + unit +
 * a short trend hint computed from the longitudinal record. The
 * Letter itself is generated by Claude Sonnet under the ANVISA
 * system prompt (`anvisa-system.ts`).
 */

export interface BiomarkerSummaryLine {
  /** pt-BR biomarker label as shown in the patient UI. */
  name: string;
  /** Current value (most recent draw). */
  value: number;
  unit: string;
  /** ISO `yyyy-mm-dd` collection date of the most recent draw. */
  collectedAt: string;
  /**
   * Free-form trend hint (e.g. "+12% across 3 draws", "stable").
   * Pre-computed by the consumer; the prompt should not have to
   * derive it. NULL when the patient only has one draw.
   */
  trend: string | null;
}

export interface BuildLetterPromptArgs {
  /** Number of confirmed draws for this patient (cold-start / baseline / fingerprint). */
  drawCount: number;
  biomarkers: BiomarkerSummaryLine[];
}

export function buildLetterUserPrompt(args: BuildLetterPromptArgs): string {
  const lines = args.biomarkers.map((b) => {
    const trend = b.trend ? ` — tendência: ${b.trend}` : "";
    return `- ${b.name}: ${b.value} ${b.unit} (coleta ${b.collectedAt})${trend}`;
  });
  const drawContext =
    args.drawCount <= 1
      ? "Este é o primeiro exame deste paciente."
      : `Este paciente tem ${args.drawCount} exames confirmados ao longo do tempo.`;
  return [
    "Você está escrevendo A Carta do Seu Eu Passado para um paciente em português brasileiro.",
    "Tom: caloroso, narrativo, em registro literário — não médico, não alarmante.",
    "Comprimento: aproximadamente 300 palavras.",
    "Abertura: a primeira frase deve de-escalonar quando houver desvios; nunca usar linguagem clínica alarmante.",
    drawContext,
    "Biomarcadores recentes:",
    ...lines,
    "Lembre-se: nunca diagnostique; sempre enquadre sugestões como 'pode valer a pena discutir com [tipo de especialista]'.",
  ].join("\n");
}
