import { index, pgEnum, pgTable } from "drizzle-orm/pg-core";

import { Users } from "./users";

/**
 * Story 4.1 — narrative Letters generated by `services/llm` (Anthropic
 * Claude Sonnet) after a draw is confirmed. Each row is the persisted
 * result of one `letter.generate` pg-boss job: created in `queued`
 * state by the enqueueing site (`packages/api/src/letters.ts` or the
 * extraction worker), flipped to `generating` when the consumer picks
 * it up, terminal at `complete` (body populated) or `failed`
 * (failureReason populated).
 *
 * Schema source: `_bmad-output/planning-artifacts/architecture.md`
 * §15 (Gap 1 resolution, lines 1450–1463).
 *
 * RLS: see `custom_rls_letters.sql` (next migration). Patients SELECT
 * own rows only; the `services/llm` worker writes via service-role
 * bypass.
 */
export const letterStatusEnum = pgEnum("letter_status_enum", [
  "queued",
  "generating",
  "complete",
  "failed",
]);

export const Letters = pgTable(
  "letters",
  (t) => ({
    id: t.uuid().notNull().primaryKey().defaultRandom(),
    // Story 5.6 FK cascade audit.
    patientId: t
      .uuid()
      .notNull()
      .references(() => Users.id, { onDelete: "cascade" }),
    /** FK target of the draw whose confirmation triggered this Letter. */
    uploadId: t.uuid().notNull(),
    status: letterStatusEnum("status").notNull().default("queued"),
    /** Full narrative body once `status='complete'`. NULL during queued/generating/failed. */
    body: t.text(),
    /** Anthropic model identifier used for generation (e.g. `claude-sonnet-4-6`). */
    model: t.text(),
    /** Sum of `usage.input_tokens + usage.output_tokens` reported by the API. */
    tokensUsed: t.integer(),
    /** Short failure code (`LETTER_UNAVAILABLE`, `RATE_LIMITED`, …). NULL on success. */
    failureReason: t.text(),
    /** Time the consumer flipped to `complete` (or `failed`). */
    generatedAt: t.timestamp({ mode: "date", withTimezone: true }),
    createdAt: t
      .timestamp({ mode: "date", withTimezone: true })
      .defaultNow()
      .notNull(),
    /**
     * Reserved for a future retention policy. NULL today; the read-path
     * helpers ignore it. Adding it now sidesteps a column-addition
     * migration on a hot table later.
     */
    expiresAt: t.timestamp({ mode: "date", withTimezone: true }),
  }),
  (table) => [
    // Story 4.2 (re-read) will SELECT by `(patient_id, created_at desc)`
    // off the Histórico tab; pre-index now since this is the only
    // anticipated read path for the table.
    index("letters_patient_created_idx").on(table.patientId, table.createdAt),
  ],
);
